#ifndef GUEST_LINUX_ERRNO_H
#define GUEST_LINUX_ERRNO_H

#define GUEST_LINUX_EIO 5
#define GUEST_LINUX_ENOMEM 12
#define GUEST_LINUX_EFAULT 14
#define GUEST_LINUX_EEXIST 17
#define GUEST_LINUX_EINVAL 22
#define GUEST_LINUX_ENOSYS 38

#endif
