#ifndef GUEST_LINUX_MEMBARRIER_H
#define GUEST_LINUX_MEMBARRIER_H

#define GUEST_LINUX_MEMBARRIER_CMD_QUERY 0U
#define GUEST_LINUX_MEMBARRIER_CMD_PRIVATE_EXPEDITED (1U << 3)
#define GUEST_LINUX_MEMBARRIER_CMD_REGISTER_PRIVATE_EXPEDITED \
    (1U << 4)
#define GUEST_LINUX_MEMBARRIER_CMD_GET_REGISTRATIONS (1U << 9)

#define GUEST_LINUX_MEMBARRIER_SUPPORTED_COMMANDS \
    (GUEST_LINUX_MEMBARRIER_CMD_PRIVATE_EXPEDITED | \
            GUEST_LINUX_MEMBARRIER_CMD_REGISTER_PRIVATE_EXPEDITED | \
            GUEST_LINUX_MEMBARRIER_CMD_GET_REGISTRATIONS)

#endif
