#ifndef GUEST_LINUX_MMAN_H
#define GUEST_LINUX_MMAN_H

// 这些值属于 Linux guest UAPI，不能替换为宿主 sys/mman.h 常量。
#define GUEST_LINUX_PROT_READ UINT64_C(0x1)
#define GUEST_LINUX_PROT_WRITE UINT64_C(0x2)
#define GUEST_LINUX_PROT_EXEC UINT64_C(0x4)
#define GUEST_LINUX_PROT_MASK (GUEST_LINUX_PROT_READ | \
        GUEST_LINUX_PROT_WRITE | GUEST_LINUX_PROT_EXEC)

#define GUEST_LINUX_MAP_SHARED UINT64_C(0x1)
#define GUEST_LINUX_MAP_PRIVATE UINT64_C(0x2)
#define GUEST_LINUX_MAP_SHARED_VALIDATE UINT64_C(0x3)
#define GUEST_LINUX_MAP_TYPE UINT64_C(0xf)
#define GUEST_LINUX_MAP_FIXED UINT64_C(0x10)
#define GUEST_LINUX_MAP_ANONYMOUS UINT64_C(0x20)
#define GUEST_LINUX_MAP_GROWSDOWN UINT64_C(0x000100)
#define GUEST_LINUX_MAP_DENYWRITE UINT64_C(0x000800)
#define GUEST_LINUX_MAP_EXECUTABLE UINT64_C(0x001000)
#define GUEST_LINUX_MAP_LOCKED UINT64_C(0x002000)
#define GUEST_LINUX_MAP_NORESERVE UINT64_C(0x004000)
#define GUEST_LINUX_MAP_POPULATE UINT64_C(0x008000)
#define GUEST_LINUX_MAP_NONBLOCK UINT64_C(0x010000)
#define GUEST_LINUX_MAP_STACK UINT64_C(0x020000)
#define GUEST_LINUX_MAP_HUGETLB UINT64_C(0x040000)
#define GUEST_LINUX_MAP_SYNC UINT64_C(0x080000)
#define GUEST_LINUX_MAP_FIXED_NOREPLACE UINT64_C(0x100000)
#define GUEST_LINUX_MAP_UNINITIALIZED UINT64_C(0x4000000)
#define GUEST_LINUX_MAP_HUGE_2MB (UINT64_C(21) << 26)
#define GUEST_LINUX_MAP_HUGE_1GB (UINT64_C(30) << 26)

// 按固定 Linux arm64 常量展开的内核历史兼容掩码；不含 SYNC 与 NOREPLACE。
#define GUEST_LINUX_MAP_LEGACY_MASK (GUEST_LINUX_MAP_SHARED | \
        GUEST_LINUX_MAP_PRIVATE | GUEST_LINUX_MAP_FIXED | \
        GUEST_LINUX_MAP_ANONYMOUS | GUEST_LINUX_MAP_DENYWRITE | \
        GUEST_LINUX_MAP_EXECUTABLE | GUEST_LINUX_MAP_UNINITIALIZED | \
        GUEST_LINUX_MAP_GROWSDOWN | GUEST_LINUX_MAP_LOCKED | \
        GUEST_LINUX_MAP_NORESERVE | GUEST_LINUX_MAP_POPULATE | \
        GUEST_LINUX_MAP_NONBLOCK | GUEST_LINUX_MAP_STACK | \
        GUEST_LINUX_MAP_HUGETLB | GUEST_LINUX_MAP_HUGE_2MB | \
        GUEST_LINUX_MAP_HUGE_1GB)

#define GUEST_LINUX_MS_ASYNC UINT32_C(1)
#define GUEST_LINUX_MS_INVALIDATE UINT32_C(2)
#define GUEST_LINUX_MS_SYNC UINT32_C(4)

#define GUEST_LINUX_MREMAP_MAYMOVE UINT64_C(1)
#define GUEST_LINUX_MREMAP_FIXED UINT64_C(2)
#define GUEST_LINUX_MREMAP_DONTUNMAP UINT64_C(4)

#define GUEST_LINUX_MADV_NORMAL 0
#define GUEST_LINUX_MADV_RANDOM 1
#define GUEST_LINUX_MADV_SEQUENTIAL 2
#define GUEST_LINUX_MADV_WILLNEED 3
#define GUEST_LINUX_MADV_DONTNEED 4

#endif
