#ifndef GUEST_LINUX_MMAN_H
#define GUEST_LINUX_MMAN_H

// 这些值属于 Linux guest UAPI，不能替换为宿主 sys/mman.h 常量。
#define GUEST_LINUX_PROT_READ UINT64_C(0x1)
#define GUEST_LINUX_PROT_WRITE UINT64_C(0x2)
#define GUEST_LINUX_PROT_EXEC UINT64_C(0x4)

#define GUEST_LINUX_MAP_SHARED UINT64_C(0x1)
#define GUEST_LINUX_MAP_PRIVATE UINT64_C(0x2)
#define GUEST_LINUX_MAP_TYPE UINT64_C(0xf)
#define GUEST_LINUX_MAP_FIXED UINT64_C(0x10)
#define GUEST_LINUX_MAP_ANONYMOUS UINT64_C(0x20)
#define GUEST_LINUX_MAP_FIXED_NOREPLACE UINT64_C(0x100000)

#define GUEST_LINUX_MADV_NORMAL 0
#define GUEST_LINUX_MADV_RANDOM 1
#define GUEST_LINUX_MADV_SEQUENTIAL 2
#define GUEST_LINUX_MADV_WILLNEED 3
#define GUEST_LINUX_MADV_DONTNEED 4

#endif
